"""Shared styling helpers for the transform tool gizmos."""

from PySide6.QtCore import Qt
from PySide6.QtGui import QColor, QCursor

TRANSFORM_DEFAULT_CURSOR = QCursor(Qt.OpenHandCursor)

TRANSFORM_GIZMO_BASE_COLOR = QColor("#0c7bdc")
TRANSFORM_GIZMO_HOVER_COLOR = QColor(TRANSFORM_GIZMO_BASE_COLOR)
TRANSFORM_GIZMO_HOVER_COLOR = TRANSFORM_GIZMO_HOVER_COLOR.lighter(130)
TRANSFORM_GIZMO_ACTIVE_COLOR = QColor(TRANSFORM_GIZMO_BASE_COLOR)
TRANSFORM_GIZMO_ACTIVE_COLOR = TRANSFORM_GIZMO_ACTIVE_COLOR.lighter(160)
